### PR TITLE
Flipster v0.5

### PR DESCRIPTION
**Pull request by shshaw**
@drien: Since my changes have been pretty significant, I went ahead and started a new branch so that I wouldn't crowd v0.4 if you need it clean.

I'm still working on this branch (primarily needing to update the demos), but wanted to open discussion if you had any thoughts or changes so far.

The biggest differences in v1 and previous versions:
* `center()` is not dependent on the 'style' setting. All major differences between Carousel and Coverflow are handled strictly in the CSS.
* `center()` no longer requires `position: absolute` for the items, and doesn't set the `left` value. Instead, the item container uses `transform: translateX` (with a fallback to `left`) to center the current item.
* A new `spacing` setting that sets a `margin-right` on each item during a `resize()` call. This can be negative, for overlapping, or positive to space the items out. The amount of spacing is relative to the individual items' size, which makes it different than just setting the margin in CSS.
* Switched to [LESS](lesscss.org) for the styles. Compressed and uncompressed css are output to the /dist/ folder via grunt.
* MouseWheel and Touch events have been rewritten that should hopefully help the interactions feel smoother.

So far everything works great in the latest versions of Chrome, Firefox, Safari & iOS Safari, but I haven't done any deeper testing.

### CODE REVIEW

**Comment by shshaw** [comment]
The following issues should be resolved with this release:
#5 #8 #10 #38 #39 #40 #49 #50

**Comment by drien** [comment]
This is great stuff, I started the 0.4 branch with good intentions and then got too busy to finish what I'd started, so its exciting to see what you've been working on. I'm all for the modernizations, I'll take a closer look when I get a chance. I'm really pleased to see the `center()` method redone, I was procrastinating about reworking all of that.  :+1: :clap: :clap:

Now that I look at it, maybe once everything is good to go we should make this into a 1.0 release, since it may no longer be compatible with the older versions. I'll look into it.

**Comment by shshaw** [comment]
Thanks! 0.4 had some great improvements that made it easy to get started.

I'd love to do some performance tests to see how much more efficient the new `center()` method is. :-) 

A 1.0 release does make sense. Everything's in a good enough state feature-wise, once the demos have been updated and browser testing complete.

Some other things I wanted to look at:
1. Making the `interactor` functions more in line with the other functions. I can't see a reason they need to be classes.
2. BEM syntax for the classes. Already started on this and it makes the classes much clearer, if not more verbose.
3. More segmented style options. Not sure of the best way to do this, but 'no-rotate' (flat) and the box-reflection transcend the 'coverflow' and 'carousel' styles. 

Once you've had a chance to look the code over more closely, let me know if there are any other changes or additions to look at!

**Comment by shshaw** [comment]
Went ahead and started the 1.0 branch.

**Pull request closed without merging**
