### PR TITLE
V1

### PR DESCRIPTION
**Pull request by shshaw**
Starting the discussion here for 1.0.

### CODE REVIEW

**Comment by shshaw** [comment]
I think functionality-wise V1.0 is ready, but I haven't been able to fully browser test yet.

My plan was to make a [gh-pages](https://pages.github.com/) branch that's just what's under the [`/demo/`](https://github.com/drien/jquery-flipster/tree/v1/demo) folder that would allow us to easily test and push changes. As I get time, I'll try to do that, but if you want to get V1 out, then feel free to start browser testing. You can let me know about any issues that pop up and I can try to debug.

**Comment by shshaw** [comment]
@drien I'm using the latest 1.0 version of Flipster on a project I'm about to launch and it's working as expected across all browsers, IE9+.

Any reason to hold off launching? If not, let's push it live.

**Comment by drien** [comment]
Sorry for not reviewing this for so long, very busy as always. Great work, I say go for it! :+1:

**Comment by shshaw** [comment]
No worries! Couldn't remember if there was anything we were holding off on other than browser testing which went quite well on my project. Doing some last minute checks then I'll push live. Thanks!

**Pull request merged**
