### PR TITLE
add css prefixes to the _container transform

### PR DESCRIPTION
**Pull request by volodymyrl**
Add css prefixes to the _container - it fixed a position bug in iPad and other devices that need css prefix

### CODE REVIEW

**Comment by shshaw** [comment]
What version of iOS was this happening in?

**Comment by volodymyrl** [comment]
jQuery v1.7.2 iPad 8.1.3

**Comment by shshaw** [comment]
Ah yes. [jQuery 1.8](https://blog.jquery.com/2012/08/09/jquery-1-8-released/) is where they added [vendor prefix support](https://bugs.jquery.com/ticket/10679). Any reason you're running 1.7?

**Comment by volodymyrl** [comment]
Thanks! Will check it and move to an other version if it possible.

**Pull request closed without merging**
